// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/SeasonScoreboardPreview.tsx": () => import("../components/mockups/SeasonScoreboardPreview.tsx"),
  "./components/mockups/cricvault/BoldModern.tsx": () => import("../components/mockups/cricvault/BoldModern.tsx"),
  "./components/mockups/cricvault/CareerLevels.tsx": () => import("../components/mockups/cricvault/CareerLevels.tsx"),
  "./components/mockups/cricvault/CleanMinimal.tsx": () => import("../components/mockups/cricvault/CleanMinimal.tsx"),
  "./components/mockups/cricvault/PremiumDark.tsx": () => import("../components/mockups/cricvault/PremiumDark.tsx"),
  "./components/mockups/palettes/Dusk.tsx": () => import("../components/mockups/palettes/Dusk.tsx"),
  "./components/mockups/palettes/Green.tsx": () => import("../components/mockups/palettes/Green.tsx"),
  "./components/mockups/palettes/Maroon.tsx": () => import("../components/mockups/palettes/Maroon.tsx"),
  "./components/mockups/palettes/Navy.tsx": () => import("../components/mockups/palettes/Navy.tsx"),
  "./components/mockups/palettes/Tawny.tsx": () => import("../components/mockups/palettes/Tawny.tsx"),
  "./components/mockups/wagon-wheel/Current.tsx": () => import("../components/mockups/wagon-wheel/Current.tsx"),
  "./components/mockups/wagon-wheel/Dynamic.tsx": () => import("../components/mockups/wagon-wheel/Dynamic.tsx"),
  "./components/mockups/wicket-info/Demo.tsx": () => import("../components/mockups/wicket-info/Demo.tsx")
};
