// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/palettes/Dusk.tsx": () => import("../components/mockups/palettes/Dusk.tsx"),
  "./components/mockups/palettes/Green.tsx": () => import("../components/mockups/palettes/Green.tsx"),
  "./components/mockups/palettes/Maroon.tsx": () => import("../components/mockups/palettes/Maroon.tsx"),
  "./components/mockups/palettes/Navy.tsx": () => import("../components/mockups/palettes/Navy.tsx"),
  "./components/mockups/palettes/Tawny.tsx": () => import("../components/mockups/palettes/Tawny.tsx")
};
